spring:
  application:
    name: shopping-cart

  jpa:
    open-in-view: false
    hibernate:
      dialect: org.hibernate.dialect.SQLServer2012Dialect
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false

  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=shopping_cart;encrypt=true;trustServerCertificate=true
    username: sa
    password: 123
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver

  mail:
    host: smtp.gmail.com
    port: 587
    username: xuanchient033@gmail.com
    password: YOUR_ID
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: YOUR_ID
            client-secret: YOUR_ID
          facebook:
            client-id: YOUR_ID
            client-secret: YOUR_ID

